cli.go
examples/example_server.go
http.go

There are a few subtypes that must have their cli registration triggered for our http server to work. This rolls all the logic into one place instead of having it spread amongst a number of function calls.

Cleanup HTTP CLI Registration

---

cli.go
examples/example_server.go

Removes Viper from the name of pflag registration commands

Remove Viper from CLI registration commands

---

kafka_mock.go

Can be used to simulate kafka consumer exit behavior

Add method to mock consumer to emit offsets

---

cli.go
examples/example_server.go
http.go

There's no reason that the http server be attached to tracing or logging config; the user of tools should be able to decide how and when they want to create the logger and tracer.

Remove logging sentry config from server

---

kafka.go

There was a race condition in the Kafka producer when it shutdown; it wasn't guaranteed to drain the messages channel. This new implementation is pretty much a by-the-book implementation from the sarama docs. Instead of using a cancel context the new to `RunProducer` API waits for the messages channel to close as a shutdown signal.

Fix race condition and proper shutdown in the kafka producer

---

examples/example_server.go
service/http.go
service/http_test.go

@briancharous what do you think of this approach? I think we define one for http, and someday one for grpc. A user could take the two cobra commands and chain them together, as well.

one-liner for a prod-compatible service

---

http/cli.go
log/cli.go
log/log.go
sentry/cli.go
tracing/cli.go

Without thinking I swapped some of the `RegisterFlags` to non-pointer receivers, which means that modified settings are lost on the command line. Oops.

use pointer for CLI registration

---

http/server.go
http/server_test.go

Turns out you have to register `/debug` with `http.DefaultServeMux` or creating profiles (i.e. /debug/pprof/profile) doesn't work and returns 404s.

register /debug path to fix pprof profile

---

examples/example_server.go
service/http.go
service/http_test.go

I was running into problems trying to configure a server that needed the environment flag defined by `service.Config` since the `RegisterHandlers` function has to be provided when creating the server cobra command. But, the actual environment value is not actually available until after the service starts up and populates its config from the CLI and/or environment variables.
So, instead of providing the `RegisterHandlers` when configuring a `service.HTTPConfig`, a function to construct the an interface with a `RegisterHandlers` method is provided when creating the server command. Then, the `ServerCmd` method can instantiate the downstream object with its configuration already populated by the CLI and/or environment variables.

Refactor service startup so that configured flags are accessible downstream

---

kafka/kafka.go
kafka/kafka_mock.go
kafka/kafka_test.go

This PR makes logging optional because if the user of the Kafka utils wants to handle the errors and log themselves, there are a lot of situations in which this library logging on its own results in duplicate logs.

Make Kafka logging optional

---

log/log.go
log/log_test.go
log/middleware.go
tracing/middleware.go

Changes the `NewContext` function in the `log` package to accept a logger instead of fields to allow more customization. For example, one might want to pass a sub-logger or a logger with additional cores or options along inside the context instead of just a logger with pre-determined fields.

Allow users to store custom logger in ctx

---

jose/cli.go
jose/cli_test.go
jose/jwt.go
jose/middleware.go
jose/middleware_test.go

By default, auth is enforced on JWT middleware. Missing bearer token == `401` if `Authorization` is missing or the `Bearer <token>` bit is malformed. `403` if the token is present but invalid.

add option to enforce auth on jwt middleware and default to true

---

kafka/producer.go

I misunderstood how cobra/viper were being used. The config values are bound to specific keys (e.g. kafka-producer-required-acks" -> ProducerRequiredAcks) and then later the env/cli vars are processed and the values are updated accordingly. By binding to a local variable we were not able to capture the new values supplied by env vars. It's not ideal, but I think we have to declare the config param as an `int` and then convert it to `sarama.RequiredAcks` later.

Fix producer required acks

---

sentry/core.go
sentry/middleware.go
sentry/middleware_test.go
sentry/sentry.go
service/http.go

This puts the Sentry recovery middleware back in place and amends the logger so that error logs that get sent to Sentry are much richer since they have request metadata. Sentry also captures the opentracing trace ID if possible and adds it to the downstream Sentry scope.

Sentry middleware

---

jose/middleware.go
jose/middleware_test.go
kafka/producer.go

currently, if auth is not required and the auth header fails to parse, the request processing short circuits and returns a 200 with no response body. This PR refactors the auth token parsing to short circuit if auth is required, but still allow further processing if it is not required.

process remaining middleware if auth is not required

---

kafka/consumer_test.go

This led to unexpected test coverage changes

Fix race condition in kafka consumer test

---

Makefile

I ran `make help` and I did not find the `build` target listed in the
help menu. I thought this project does not have it, but after checking
the `Makefile`, I found that target.
This change provides help menu text for all other Makefile targets.
Before:
```
% make help
coverage                       Displays test coverage report
help                           Prints this help command
lint                           Runs the go code linter
test                           Runs application tests
```
After:
```
% make help
all                            Lints and runs the tests
build                          Builds the project
coverage                       Displays test coverage report
example-server                 Builds an example server
help                           Prints this help …
```

Add other tasks' help descriptions

---

tracing/middleware.go
tracing/middleware_test.go

This PR adjusts the implicit contract of `GetCorrelationID()` such that the function now avoids returning a nillable `string` type.

GetCorrelationID() result now non-nillable for safety/ergonomics

---

http/parsers.go
http/parsers_test.go

This PR introduces reusable query parameter parsers, specifically:
- ParseCoordinates
- ParseTime
@briancharous @greg-mclain just CCing you in on this PR as tools users

Http query parsers

---

go.mod
go.sum
log/middleware.go
log/middleware_test.go
sql/metrics.go
sql/metrics_test.go
sql/middleware/middleware.go
sql/middleware/middleware_test.go
sql/mysql.go
sql/postgres.go
tracing/middleware.go

* Adds a wrapped MySQL db connection so that MySQL database interactions can be wrapped with the same tracing, logging, and metrics as the Postgres wrapper
* Makes naming queries optional so that the wrappers can be used with libraries other than sqlx (including the standard library sql module) that don't necessarily accept a context for database operations.

Adds MySQL wrapper w/middleware & removes named query requirement

---

log/grpc_interceptors.go
log/grpc_interceptors_test.go
log/log.go
log/middleware.go
log/middleware_test.go

* Replaces the GRPC logger with our zap logger
* Makes `request received` log messages Debug, as we discussed, to cut down on excess logging

Instrument the GRPC server and make request received log at Debug

---

grpc/server.go
grpc/server_test.go
service/cli.go
service/example_test.go
service/service.go
service/service_test.go

This PR adds pre-start and post-shutdown functions into to the `service` package and changes the gRPC server startup behavior.
* Pre-start and post-shutdown functions now exist at the service-level take a `context.Context`, enabling state passing between those two functions.
* gRPC `Run` is now non-blocking; instead, if the server can't startup, it will return an error immediately. If it can, it returns a channel that gets closed when it exits.
* The HTTP server now starts with metrics and health check endpoints, even if the user hasn't specified an HTTP server handler.
* I can't 100% confirm it, but I believe I fixed hanging tests.

Service pre-start and post-shutdown functionality

---

go.sum
sql/cli.go
sql/cli_test.go
sql/mysql.go
sql/postgres.go
sql/postgres_test.go
sql/sql.go
sql/sql_test.go

My main motivation for this PR was to allow overriding the registered name of the wrapped driver. Instead of taking on another parameter to the constructor(s), I added functional options with nice defaults. Also, I unified the way that Postgres and MySQL connection API.
An example of how this can be used if you wanted to override the metrics collection frequency and driver name:
```go
cfg := sql.MySQLConfig{
// connection options in here //
}
conn, dbClose, err, := cfg.Connect(
context.Background(), 
sql.WithMetricsCollectionFrequency(10 * time.Second), 
sql.WithDriverName("override-driver"))
```

Unifies MySQL and Postgres connection options & allows wrap overrides

---

jose/auth0.go
jose/auth0_test.go
service/service.go

Adds Auth0 support to tools. This is largely in support of CRaiG and vehicles work for @wilsoniya and @theisenmark. Once this is merged, incoming JWTs will automatically be parsed for ClientID / UserID information which will then be placed into the context for all downstream services.
See here: https://auth0.com/docs/scopes/current/sample-use-cases#add-custom-claims-to-a-token for information on where standard OpenID fields came from

basic auth0 support

---

http/client.go
http/client_test.go

Quick bugfix to use the specified metrics instance in the default http client.

Use specified metrics instance in default http client

---

service/service.go

Sadly the environment setting for the sentry config was set too early, so all of our deployments were filing their errors under `local`, always. This enables us to have environment routing work correctly.

env set in wrong place for sentry

---

jose/auth0.go
jose/auth0_test.go

https://spothero.atlassian.net/browse/PMP-480
This PR:
- adds a convenience function for extracting an Auth0 claim from a Context
- adds accessor functions for extracting `UserID` and `ClientID` from Auth0 claims

Pmp 480 auth0 claim adjustments

---

jose/cli.go
jose/cli_test.go
jose/grpc_interceptors.go
jose/grpc_interceptors_test.go
jose/jwt.go
jose/jwt_test.go
jose/middleware.go
jose/middleware_test.go
service/service.go

This gets rid of the concept of a globally enforced auth. We'll only ever enforce it on GRPC endpoints, HTTP routers, or HTTP Handlers. This was a broken idea that didn't work correctly.

rm auth required

---

pagination/paginator.go
pagination/paginator_test.go

This is the same pagination code originally written by @wilsoniya for CRAiG - https://github.com/spothero/craig/pull/40
I'm trying to reuse it in `reservations` so I figure it's a good candidate to extract into our common tooling.

Add basic pagination support

---

service/service.go

**Issue Link**
https://spothero.atlassian.net/browse/PMP-542
Use first 6 chars of git sha when logging to be consistent w/ git's own abbreviated commits (which gh uses, also).

[PMP-542] use first 6 chars of git sha for logging

---

go.mod
http/server.go

This is all that's required to get cleartext HTTP/2 (aka h2c) connections going. By default `net/http` accepts connections over HTTP/2, but only if TLS is enabled.
Internally, the reason we want h2c turned on is so that we can accept both standard HTTP requests as well as gRPC requests over the same Kubernetes ingress.

Allow h2c connection upgrade

---

currency/doc.go
currency/example_test.go

Use `currency` as a first example of how we want to do package documentation.

Add package documentation for currency

---

pagination/doc.go
pagination/example_test.go
pagination/paginator.go
pagination/paginator_test.go

I could not fine anywhere that [IDExtractor](https://godoc.org/github.com/spothero/tools/pagination#IDExtractor) is used.
If it is not used, should we remove it from the package?

Add pagination package documentation

---

currency/example_test.go
log/example_test.go
service/doc.go

Was getting lint errors that were somehow not caught and rejected by the circleci stuff in the first PR: https://github.com/spothero/tools/pull/128
These occur because `go vet` expects Example function names to be valid identifiers in the package.
Seems kinda limited to me.
In addition, forgot to run `go fmt ./...` on a couple files.
```
log/example_test.go:12:21: Error return value of `c.InitializeLogger` is not checked (errcheck)
+ l/example_test.go
c.InitializeLogger()
^
log/example_test.go:10:1: tests: ExampleInitialize refers to unknown identifier: Initialize (govet)
func ExampleInitialize() {
^
log/example_test.go:16:1: tests: ExampleCreate refers to unknown identifier: Create (govet)
func ExampleCreate() {
^
log/example_test.go:23:1: tests: ExampleMiddlewareHTTP refers to unknown …
```

Fix lint errors

---

log/doc.go

log pkg docs were not showing up here: https://pkg.go.dev/github.com/spothero/tools
Maybe because of package doc comment format ?
Doing a /bump patch so that a new public version is released and is sure to be picked up.

Use // comments in log pkg docs

---

jose/example_test.go
jose/jwt.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-1119
Removes the unused `AuthRequired` param.
Ben started the process here - https://github.com/spothero/tools/pull/115. This should take it across the finish line.

SEAR-1119 Remove unused AuthRequired param

---

kafka/schema_registry.go
kafka/schema_registry_test.go
kafka/unmarshal_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SIQ-328
This change enhances the schema registry client to add support for new APIs:
- CheckSchema: checks if a schema is exists in the registry
- CreateSchema: creates a new schema in the registry

Implement schema registry enhancements

---

http/metrics.go
http/metrics_test.go

**Issue Link**
N/A
This change will handle a case where AlreadyRegisteredError is returned from Prometheus when registering a collector.  In this case, the existing collector will be returned.

Handle AlreadyRegisteredError when creating new http metrics

---

cors/cli.go
cors/cli_test.go
cors/cors.go
cors/middleware.go
cors/middleware_test.go
service/service.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-1239
Adds optional CORS middleware for HTTP servers.

SEAR-1239 Add optional CORS middleware for HTTP servers

---

grpc/client.go
grpc/client_test.go
sql/postgres_test.go

Previously, only insecure default configuration  was available for grpc clients.
This PR provides a default configuration for TLS as well.
In addition to the unit tests, this code has been tested with some [e2e tests](https://github.com/spothero/craig/pull/394/files#diff-80e4f1cfacabf5afef6b0280e94c50e993c08949586151655ea619ff0aa5166aR4189-R4190)

DTS-485 Add tls support for grpc clients

---

currency/doc.go
log/doc.go

Some time ago I started adding package documentation.   I noticed that not all of it is showing up at https://pkg.go.dev/github.com/spothero/tools 
This PR tweaks the format in an attempt to get the documentation picked up and searchable by the community.

Attempt to make currency and log docs visible at pkg.go.dev

---

sentry/core_test.go
sentry/sentry.go
sentry/sentry_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-1541
Adds option to disable Sentry integration. Sentry is still enabled by default.

SEAR-1541 Add option to disable Sentry integration

---

jose/auth0.go
jose/auth0_test.go
jose/middleware.go
jose/middleware_test.go
strings/strings.go
strings/strings_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SIQ-531
This change will allow authorization against a slice of required scopes.  Each of the required scopes must exist in the scope taken from the token to complete authorization.

SIQ-531 Add functionality to authorize on scope

---

jose/middleware.go
jose/middleware_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SIQ-531
This PR fixes an issue were requiredScopes was not exported making it inaccessible from downstream projects that want to use this functionality.

SIQ-531 Fix issue were the requiredScopes field was not exported

---

jose/example_test.go
jose/jwt.go
jose/jwt_test.go
service/service.go

**Issue Link**
https://spothero.atlassian.net/browse/CONWEB-1484
Lazy loads JWKS public keys.
Previously, apps using the `jose` package would fail to boot up if any of their configured JWKS urls were unreachable.
With this update, apps will still try to retrieve public keys from each configured JWKS URL as they boot up. However, if any of the URLs do not send back a valid set of public keys the app will now simply log an error and continue booting up. The next time the app attempts to decode an incoming token, it will retry the request to fetch the corresponding public keys. Until the keys are able to be fetched, authenticated requests will fail with a 403 error.

CONWEB-1484 Lazy load JWKS public keys

---

cli/cli.go
grpc/client.go
grpc/client_test.go
kafka/schema_registry.go
log/log.go
sql/postgres.go
sql/postgres_test.go
tracing/cli.go
tracing/cli_test.go

`make test` was failing on macos 12
See https://github.com/golang/go/issues/41572#issuecomment-700232101 for more info.

Avoid SIGABRT on IP lookup macos 12

---

http/metrics.go
http/metrics_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-2441
This PR moves our request counter metric to increment when the request is received and adds a new requests returned metric.

SEAR-2441 track req received before return; add req returned metric

---

http/metrics.go
http/metrics_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-3282
This pr adds method to the http metric labels so that we can analyze them separately.

SEAR-3282-add-http-method-to-http-metrics

---

concurrency/worker_pool.go

**Issue Link**
[SEAR-3389](https://spothero.atlassian.net/browse/SEAR-3389)
- Exposing LoopTimeout and SleepTime as public constant.
[SEAR-3389]: https://spothero.atlassian.net/browse/SEAR-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SEAR-3389: Exposing LoopTimeout and SleepTime as public constant.

---

sentry/core.go

**Issue Link**
[SEAR-3379](https://spothero.atlassian.net/browse/SEAR-3379)
- generating sentry fingerprint based on error message instead of stack-trace
[SEAR-3379]: https://spothero.atlassian.net/browse/SEAR-3379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SEAR-3379: generating sentry fingerprint based on error message instead of stack-trace

---

go.mod

**Issue Link**
ADHOC
Bumps up to Go version 1.22.4 to address a vulnerability reported by `govulncheck`.
```
govulncheck ./...
Scanning your code and 504 packages across 72 dependent modules for known vulnerabilities...
Vulnerability #1: GO-2024-2887
Unexpected behavior from Is methods for IPv4-mapped IPv6 addresses in
net/netip
More info: https://pkg.go.dev/vuln/GO-2024-2887
Standard library
Found in: net/netip@go1.22.3
Fixed in: net/netip@go1.22.4
Example traces found:
#1: kafka/client.go:47:33: kafka.Config.NewClient calls sarama.NewClient, which eventually calls netip.Addr.IsLoopback
#2: kafka/client.go:47:33: kafka.Config.NewClient calls sarama.NewClient, which eventually calls netip.Addr.IsMulticast
Your code is affected by 1 vulnerability from the Go standard …
```

ADHOC - Bump up to Go version 1.22.4

---

jose/auth0.go
jose/auth0_test.go

**Issue Link**
MOB-477
- This Pr fixes the error when `jwt` was trying to unmarshal `gty` auth0 custom claims. In Auth0, when the token is get from the /token API, it comes as a string, but the token from the refresh token comes as an array, i.e ["refresh_token", "password"]. Therefore this PR makes the grant type field an interface in Auth0Claim

[MOB-477] Fixes the Auth0Claims for Refresh token

---

jose/auth0.go
jose/auth0_test.go

**Issue Link**
ADHOC
Handles Auth0 claims with `GrantType == nil`

ADHOC - Handle Auth0 claims with nil grant types

---

.golangci.yml
Makefile
grpc/server.go
http/metrics_test.go
http/parsers_test.go
jose/middleware_test.go
kafka/client.go
kafka/schema_registry.go
kafka/unmarshal.go
pagination/paginator_test.go
service/service.go
time/time_test.go
tracing/middleware_test.go
tracing/tracing_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-3612
This PR fixes all linting errors after upgrading our `golangci-lint` version to `1.59.1`. Depends on https://github.com/spothero/mdw/pull/370

SEAR-3612 Fix linting errors for golangci-lint version 1.59.1
