Gopkg.lock
Gopkg.toml

Use versions instead of specific revisions

Specify versions instead of revisions

---

cli.go
kafka.go
kafka_mock.go
kafka_test.go

Refactors the creation of Kafka producers and consumers such that multiple producers and consumers can be created from the same client object.

Refactor Kafka creation

---

.circleci/config.yml
Makefile
examples/example_server.go
http.go
kafka_test.go
kafka_utils_test.go
logging.go
sentry.go
tracing.go

Fixes linting issues and overhauls makefile to our newer standards.

cleanup makefile with lint and fix linter issues

---

Makefile
examples/example_server.go
go.mod
go.sum
http/server.go
sentry/sentry.go
service/cli.go
service/cli_test.go
service/http.go
service/http_test.go

@briancharous I realized I glossed over some of the CLI config for the generic http service. This just adds that back and makes it a bit more common.

service CLI improvements

---

http/server.go
http/server_test.go

listen address now defaults to localhost

---

http/server.go

Simplifies the HTTP server logic so now it properly shuts down when a cancel signal is received. It now only performs the following (ignoring pre/post hooks):
1) Creates a cancellable context to be passed into app modules.
2) Executes ListenAndServe in a separate go-routine
3) Blocks and waits for a cancel signal in the main thread
4) When a signal is received, call shutdown with a timeout context (which will force ListenAndServe to return)
5) Cancels all contexts

Fix graceful shutdown of HTTP server

---

Makefile

minor tweaks to make the build/run procedure in README work

make README work

---

kafka/producer.go

Fix documentation for RegisterFlags function, takes care of linter warning

---

tracing/middleware.go
tracing/middleware_test.go

This PR adjusts the tracing HTTP middleware to add the jaeger trace id to the HTTP request context as a correlation ID. I'm making this addition for ergonomics and also to avoid the opentracing/jaeger leaky abstraction from leaking out of this package.

Adds correlation id to incoming HTTP request contexts

---

README.md

Fix the file path for example_server.go

---

http/parsers.go
jose/grpc_interceptors_test.go
jose/jwt.go
jose/middleware_test.go
kafka/client.go

Removes xerrors from tools, since we're upgrading to 1.13 and this functionality is now included in `fmt.Errorf`

Rm xerrors

---

http/client.go
http/client_test.go

improve defaults and docs, use set for retriable codes

---

kafka/cli.go
kafka/cli_test.go

And remove some commented out code

Rename Kafka broker flag & description

---

service/service.go

This PR updates service to avoid calling `newGRPCService` outside of `RunE`; equivalently, `newGRPCService` and `newHTTPService` are now effectively called from within the same scope and so should have access to equivalent environments.

ServerCmd now avoid evaluating newGRPCService closure outside RunE

---

currency/conversions.go
currency/conversions_test.go

handle negative remainder values

---

jose/grpc_interceptors.go
jose/grpc_interceptors_test.go
tracing/tracing.go

Fixes the broken header propagation for the grpc clients

correct broken header propagation

---

http/metrics.go

fixes a panic if this is called too early.

rm logging and clean up code, logger may not yet be initialized

---

kafka/consumer.go
kafka/consumer_test.go

change kafka message gauges to counters

---

jose/middleware.go
jose/middleware_test.go

https://spothero.atlassian.net/browse/PMP-508
This PR adds authentication enforcement middleware and utilities to tools.

[PMP-508] added authentication enforcement middleware utils

---

jose/cli.go
jose/cli_test.go
jose/example_test.go
jose/jwt.go
jose/jwt_test.go

Allows multiple JWKS URLs so we can work with both Cognito and Auth0 at once.

allow specification of multiple jwks urls

---

jose/cli.go
jose/cli_test.go
jose/example_test.go
jose/jwt.go
jose/jwt_test.go

Turns out this also needs multiple field support

multiple valid issuers

---

jose/jwt.go

Fix the bug where I used the same variable twice and didnt do anything with it 🤡

actually set the array values :facepalm

---

http/parsers.go
http/parsers_test.go

**Issue Link**
https://spothero.atlassian.net/browse/PMP-589
Specify accepted layouts when parsing datetime query params.
This is to accommodate endpoints that accept datetimes in multiple formats. For example - http://availability.production.spothero.com/docs#tag/searchByLatLon

PMP-589 Specify accepted layouts when parsing datetime query params

---

pagination/example_test.go
sql/mysql_test.go

circleci was still failing even after merging https://github.com/spothero/tools/pull/134
This seems to fix it for real.

Fix circleci errors

---

log/doc.go
log/example_test.go

Add log package documentation

---

sql/middleware/doc.go

Add sql/middleware package documentation

---

service/doc.go

Add service package documentation

---

cli/doc.go

Add cli package documentation

---

kafka/client_test.go

Add test coverage

---

jose/grpc_interceptors.go
jose/middleware.go

This PR adjusts bumps up the log level on JOSE auth failures

Increases log level on JOSE failures

---

http/server.go
http/server_test.go
log/log.go

Adds the ability to change the global log level of an application.

add support for global dynamic log level

---

.circleci/config.yml
go.mod
go.sum
http/server.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-1285
Enable gzip compression

SEAR-1285 enable gzip compression in server middleware

---

jose/auth0.go

https://spothero.atlassian.net/browse/OCP-823

Add spothero namespace to claim struct email property

---

grpc/client.go
http/metrics_test.go
kafka/schema_registry.go
kafka/schema_registry_test.go
sql/postgres_test.go

**Issue Link**
NA
I found that some of the existing source files were not formatted when development the authorization by scope feature.  This PR will format these files to bring them up to the standard.

Format existing source code

---

kafka/schema_registry.go
kafka/schema_registry_mock.go

Adds interfaces and a mock client for schema registry client to enable unit testing in applications.

add interfaces and mock client for schema registry client

---

service/service.go

Revert "feature/SEAR-2188-move-up-auth-middleware"

---

sentry/core.go
sentry/core_test.go
sentry/middleware.go

**Issue Link**
https://spothero.atlassian.net/browse/SIQ-1112
Add tag method for sentry core log
Fix With to append instead of replace

[SIQ-1112] Add tag method for sentry core log

---

jose/auth0.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-2696
This PR removes some outdated Cognito references. It also removes a couple unused constants.

SEAR-2696 Remove Cognito references

---

sentry/core.go
sentry/core_test.go

**Issue Link**
https://spothero.atlassian.net/browse/SIQ-1151
New field type so that we can separate issues in Sentry based on inputs

Add Fingerprint field type for the sentry zap appender

---

grpc/server.go

- Revert buffer size changes, as it's not very impactful.

SEAR-2990: Revert buffer size changes, as it's not much impactful.

---

Makefile
concurrency/worker_pool.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-3344
In this pr, I set the worker count to runtime.NumCPU() and lower the sleep.

SEAR-3344-tweak-worker-count

---

go.mod

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-3317

update go to 1.22.1

---

go.mod
go.sum

- fix net package vulnerability issue

ADHOC: fix net package vulnerability issue

---

go.mod
go.sum
kafka/cli.go
kafka/client.go
kafka/client_test.go
kafka/consumer.go
kafka/consumer_test.go
kafka/producer.go
kafka/producer_test.go
kafka/schema_registry.go
kafka/schema_registry_mock.go
kafka/schema_registry_test.go
kafka/unmarshal.go
kafka/unmarshal_test.go

https://spothero.atlassian.net/browse/SEAR-3520
- Migrate `sarama` from Shopify to IBM package

SEAR-3520: migrate sarama from Shopify to IBM package

---

http/server.go
http/server_test.go

https://spothero.atlassian.net/browse/SEAR-3534
- disable debug endpoints by default.

SEAR-3534: disable debug endpoints by default.

---

log/middleware.go

**Issue Link**
https://spothero.atlassian.net/browse/SEAR-3677
This converts a high volume info log into a debug log to reduce logging volume.

SEAR-3677-trim-logs
